services:
  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: youbahn/chat-api
    environment:
      CADDY_GLOBAL_OPTIONS: debug
      SERVER_NAME: http://localhost
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: node:20
    ports:
      - 5173:5173
      - 35729:35729
    volumes:
      - .:/app
    working_dir: /app
    command:
      - yarn
      - dev

  horizon:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: youbahn/chat-api
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: "php artisan horizon"

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  pusher:
    image: quay.io/soketi/soketi
    environment:
      SOKETI_DEBUG: 1
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
      SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY}
      SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET}
    ports:
      - 6001:6001
      - 9601:9601

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025

volumes:
  mysql-data:
  redis-data:
